### ISSUE TITLE
Missing fixtures

### ISSUE THREAD

**Issue by karensg** [TrailerVote/trailervote-fixtures#27]
no fixture for application/vnd.trailervote.place.v4.create+json
no fixture for application/vnd.trailervote.product.image.v1.create+json
no fixture for application/vnd.trailervote.sentiment_feedback.v2+json
no fixture for application/vnd.trailervote.persona.v1.create+json
no fixture for application/vnd.trailervote.audio_fragment.v1.collection+json
no fixture for application/vnd.trailervote.product.v2.collection+json
no fixture for application/vnd.trailervote.product.video.v1.create+json
no fixture for application/vnd.trailervote.configuration.v3+json
no fixture for application/vnd.trailervote.product_place_link.v1+json

**Comment by louisraymond** [comment]
- [x]  fixture for application/vnd.trailervote.place.v4.create+json
- [x]  fixture for application/vnd.trailervote.product.image.v1.create+json
- [x]  fixture for application/vnd.trailervote.sentiment_feedback.v2+json
- [x]  fixture for application/vnd.trailervote.persona.v1.create+json
- [x]  fixture for application/vnd.trailervote.audio_fragment.v1.collection+json
- [x]  fixture for application/vnd.trailervote.product.v2.collection+json
- [x]  fixture for application/vnd.trailervote.product.video.v1.create+json
- [x]  fixture for application/vnd.trailervote.configuration.v3+json
- [x]  fixture for application/vnd.trailervote.product_place_link.v1+json

**Comment by louisraymond** [comment]
Question: How do I test these against the media types library? I want to do this before refactoring/adding parts/submitting a merge request

**Comment by karensg** [comment]
In media-types library, change gemfile to point to local fixtures gem and
run tests.

**Comment by louisraymond** [comment]
- [x] application/vnd.trailervote.product.image.v1.collection+json
- [x] application/vnd.trailervote.place.v4.index+json  
- [x] application/vnd.trailervote.product_place_link.v1.collection+json 
- [x] application/vnd.trailervote.product.video.v1.collection+json
- [x] application/vnd.trailervote.product.v2.create+json

**Comment by thexa4** [comment]
- [ ] https://views.stable.trailervote.com/trailervote-views-api/audio-recognition
 - [ ] https://cta.trailervote.com/12208e66d70902e5b187b305ea13f35acc8e4d48779270b672cfcee44b8a501995e2
 - [ ] https://views.stable.trailervote.com/trailervote-views-api/adbutler-banner?campaign_id=273737&advertiser_id=102141&banner_id=519655431
 - [ ] https://views.stable.trailervote.com/trailervote-views-api/cinepolis-deeplink?deeplink=cinepolis://test
